'use client';

import { KanbanProvider } from '@/systems/kanban/context';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ApplicationLayout } from './application-layout';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} text-zinc-950 antialiased lg:bg-zinc-100 dark:bg-zinc-900 dark:text-white dark:lg:bg-zinc-950`}
    >
      <body>
        <KanbanProvider>
          <ApplicationLayout>{children}</ApplicationLayout>
        </KanbanProvider>
      </body>
    </html>
  );
}
